# Site settings
title: "XiongXiaomao blog"
email: yarkivaev@gmail.com
description: >-
  Travel blog documenting adventures around the world. 
  一边 программируем 一边 путешествуем - Programming while traveling.
author:
  name: "Yaroslav Kivaev"
  email: "yarkivaev@gmail.com"
  twitter: ""
  github: "yarkivaev"
lang: "en_US"

# URLs
baseurl: ""
url: "https://2xiaomao.ru"
enforce_ssl: "2xiaomao.ru"

# Social and SEO
github_username: yarkivaev
twitter:
  username: 
  card: summary_large_image
facebook:
  app_id: 
  publisher: 

# Google and Analytics
google_analytics: 
google_site_verification: 
# yandex_verification: 

# Images and Media
logo: "/assets/images/logo.png"
social:
  name: "Yaroslav Kivaev"
  links:
    - "https://github.com/yarkivaev"

# Comments
disqus:
  shortname: xiaomao-blog

# Content settings
show_excerpts: true
paginate: 6
paginate_path: "/page:num/"

# Taxonomy
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  travel:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: "_posts/travel"
      type: posts
    values:
      layout: post
      categories: [travel]
      author: "Yaroslav Kivaev"
      comments: true

# Build settings
markdown: kramdown
highlighter: rouge
incremental: false
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Compression
compress_html:
  clippings: all
  comments: all
  endings: html
  blanklines: false
  profile: false

# Performance
liquid:
  error_mode: warn

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
